Repository injectablerb/injectable, pull requests merged in 2019-04, with the labels that each got.

#1 master|anthony/gemify-injectable
  CODE_OF_CONDUCT.md
  Gemfile.lock
  injectable.gemspec
  lib/injectable.rb
  lib/injectable/class_methods.rb
  lib/injectable/dependencies_graph.rb
  lib/injectable/dependencies_proxy.rb
  lib/injectable/dependency.rb
  lib/injectable/instance_methods.rb
  lib/injectable/missing_dependencies_exception.rb
  lib/injectable/version.rb
  spec/injectable/dependencies_graph_spec.rb
  spec/injectable/dependencies_proxy_spec.rb
  spec/injectable/dependency_spec.rb
  spec/injectable_spec.rb
  spec/spec_helper.rb
Labels: Needs Changes

#5 Fix code of conduct link.
  README.md
Labels: Needs Review

#4 master| Moving over updates to dependency resolution from Rocto branch.
  lib/injectable/class_methods.rb
  lib/injectable/dependencies_graph.rb
  lib/injectable/dependencies_proxy.rb
  lib/injectable/dependency.rb
  spec/injectable/dependencies_graph_spec.rb
  spec/injectable/dependencies_proxy_spec.rb
  spec/injectable/dependency_spec.rb
  spec/injectable_spec.rb
Labels: Ready for merge
